### ISSUE TITLE
Skin Development

### ISSUE THREAD

**Issue by LeeThompson** [brablc/sitebar#8]
I'm developing my own skin but it seems no matter what font sizes I select in my css files they're being overridden somewhere (except for the stats and powered by footer).

**Comment by brablc** [comment]
I have not notice there are any issues on this project since I created it. My bad. I guess you are no more interested in any advice.

**Comment by paoloschi** [comment]
but I'm! today I've encountered the same difficulty reported by LeeThompson and I would like to resolve it..

**Comment by brablc** [comment]
Can you be more specific? Can you copy your CSS which is not working?

**Comment by paoloschi** [comment]
I made a copy of the 'sidebar/skins/Classic' folder (for not to change the original).
My purpose for now is just to get a magnification of characters because I struggle to read them..
So what I did was edit the file 'common.css' to increase from 8 to more the px value here:

```
.siteBarBaseFont
{
    font-family: Verdana, Tahoma, Geneva, Arial, Helvetica, sans-serif;
    font-size: 10pt;
}
```

but refreshing the page I see that the font remains of the same size..
btw, I would also ask if there is documentation for the development of the skins that I should read before to try as I did..

**Comment by brablc** [comment]
Apparently `body.siteBar` wins as more specific. You can try specifying this as `body.siteBar.siteBarBaseFont`

**Comment by paoloschi** [comment]
If I apply your suggestion to 'common.css' I do not see any changes but you gave me the thought  to introduce the `font-size:` property into 'sitebar.css' file instead, which was not present in the original 'Classic' skin source:

```
@charset "utf-8";
@import url("../sitebar.css");
@import url("common.css");

body.siteBar
{
    margin: 0px 2px;
    font-size: 10pt;           /*  <---- my addition  */
}

[..]
```

Doing so I get the desired result: I can now adjust the font size as I want!
If that may be a acceptable solution, as for me this issue can be closed.
thx!

**Comment by brablc** [comment]
Well, this seems a better solution, at least it bypasses problem with cached styles. Thanks for your feedback.
